<h2>Biografia</h2>

<p>
Nasce a Perugia nel 1962. Studi musicali accademici in Pianoforte, Organo e Composizione Organistica, Clavicembalo, Composizione e Direzione d' Orchestra. Ha frequentato <strong>corsi di alto perfezionamento</strong> studiando con G. Scotese, W.Van de Pol, A. Conti, E. Fadini, E. Riboli, L . F. Tagliavini,  J. L. Gonzales Uriol,  M. Morgan, L. Lombardi, T. Kopman. Ha svolto attività concertistica nelle principali città europee, negli Stati Uniti d'America e nel Continente Africano. Il suo interesse musicale è sempre stato sin dalla tenera età concentrato nella composizione dedicandosi alla <strong>ricerca di sonorità innovative</strong> sia con strumenti convenzionali, sia con dispositivi elettronici seguendone l'evoluzione tecnologica, consolidando un suo <strong>stile originale, diretto e comunicativo</strong>, rivolto a varie fasce di pubblico. Le sue musiche sono state trasmesse da <strong>Rai Uno, Rai International, Mediaset</strong>, dalle tre emittenti radiofoniche della RAI, Radio Vaticana ed eseguite nell’ambito di prestigiosi festivals internazionali. Ha dedicato, scritto e scrive per notissimi artisti del panorama internazionale tra i quali Elisabeth Leonskaja, Murray Perahia, Laura De Fusco, W. Van de Pol, Michel Petrucciani e Antonella Ruggiero. Ha inoltre composto per la <strong>Biennale Musica di Venezia</strong>, per il <strong>Teatro G. Pergolesi di Jesi</strong> inaugurando la Stagione Lirica 2003/04 con l'Opera "Pollici Verdi" e, recentemente, per Eugene Rousseau, Ramin Bahrami, e Stefano Bollani. </p>

<h3>Composizioni e concorsi a livello internazionale</h3>

<p>
Vincitore di numerosi <strong>concorsi internazionali di composizione</strong>, ha nel suo attivo circa 400 composizioni comprendenti musica per pianoforte, organo, musica da camera in svariate formazioni, musica vocale, sinfonica, sinfonico corale e musica elettronica interattiva con strumenti tradizionali, tra le più significative: <i>Asincrone</i>, per Sequenze Elettroniche e Pianoforte (1989); <i>Concerto in Sol Maggiore</i>, per Flauto e Orchestra d'Archi (1991); <i>Toccata</i>, per Pianoforte (2002); <i>Mosaico Tritonale</i>, per Orchestra Sinfonica (2003); <i>Te Deum</i>, per Soli, Coro, Organo e Orchestra (2003); <i>Magnificat</i>, per Doppio Coro e Organo (2004); <i>Stabat Mater</i>, per Soli, Coro e Orchestra (2006); <i>Paesaggio Umbro</i>, per Violoncello, Quartetto d'Archi, Voci e Pianoforte (2007); <i>Il Cantico delle creature di S. Francesco d'Assisi</i>, Oratorio per Tenore, Coro e Orchestra (2008); <i>San Francesco d'Assisi predica agli uccelli</i>, per Orchestra Sinfonica (2008); <i>Requiem Strumentale</i>, per Saxofono Soprano e Pianoforte (2009); <i>Fantasia Concerto</i>, per Pianoforte e Orchestra (2009); <i>Sei Contrappunti</i>, per Pianoforte I° Volume (2010); <i>Sei Contrappunti</i>, per Pianoforte II° Volume (2012); <i>Dissolvenze Atonali</i>, per Quartetto di Saxofoni, <i>Pianoforte e Sequenza Elettronica</i> (2012); Parte delle sue composizioni sono pubblicate in CD dalle case discografiche Amiata Records, Columbia-Sony, Libera, Rara, Umbria Music Center, mentre la pubblicazione della sua intera opera omnia è curata dalla "Casa Editrice Musicale Prendinota". 
</p>