<p>
	<a class="fancybox" rel="photos" href="<?=ROOT?>img/rossi_hires.png">
		<img class="lazy left" style="border:1px solid #000; margin-bottom:10px;" src="<?=ROOT?>img/trans.gif" data-original="<?=ROOT?>img/rossi_hires.png" width=300 alt="Antonio Rossi Composer">
	</a>

	<?php if ($lang == 'it') { // ITALIAN BIO ?>
	
	Nasce a <b>Perugia</b> nel 1962. Studi musicali accademici in Pianoforte, Organo e Composizione Organistica, Clavicembalo, Composizione e Direzione d' Orchestra. Ha frequentato <strong>corsi di alto perfezionamento</strong> studiando con G. Scotese, W.Van de Pol, A. Conti, E. Fadini, E. Riboli, L . F. Tagliavini,  J. L. Gonzales Uriol,  M. Morgan, L. Lombardi, T. Kopman. Ha svolto attività concertistica nelle principali città europee, negli Stati Uniti d'America e nel Continente Africano. Il suo interesse musicale è sempre stato sin dalla tenera età concentrato nella composizione dedicandosi alla <strong>ricerca di sonorità innovative</strong> sia con strumenti convenzionali, sia con dispositivi elettronici seguendone l'evoluzione tecnologica, consolidando un suo <strong>stile originale, diretto e comunicativo</strong>, rivolto a varie fasce di pubblico. Le sue musiche sono state trasmesse da <strong>Rai Uno, Rai International, Mediaset</strong>, dalle tre emittenti radiofoniche della RAI, Radio Vaticana ed eseguite nell’ambito di prestigiosi festivals internazionali. Ha dedicato e composto musica per <strong>notissimi artisti del panorama internazionale</strong> tra i quali <a href="http://it.wikipedia.org/wiki/Elisabeth_Leonskaja">Elisabeth Leonskaja</a>, <a href="http://it.wikipedia.org/wiki/Murray_Perahia">Murray Perahia</a>, <a href="http://it.wikipedia.org/wiki/Laura_De_Fusco">Laura De Fusco</a>, W. Van de Pol, <a href="http://it.wikipedia.org/wiki/Michel_Petrucciani">Michel Petrucciani</a> e <a href="http://www.antonellaruggiero.com/">Antonella Ruggiero</a>. Ha inoltre composto per la <strong>Biennale Musica di Venezia</strong>, per il <a href="http://www.fondazionepergolesispontini.com/fps/index.php?option=com_content&view=article&id=103&Itemid=339&lang=it"><strong>Teatro G. Pergolesi di Jesi</strong></a> inaugurando la Stagione Lirica 2003/04 con l'Opera "Pollici Verdi" e, recentemente, per Eugene Rousseau, <a href="http://it.wikipedia.org/wiki/Ramin_Bahrami">Ramin Bahrami</a> e <a href="http://www.stefanobollani.com/">Stefano Bollani</a>.
	
	<?php } else { // ENGLISH BIO ?>
	
	He was born in <b>Perugia</b> (Italy) in 1962. Academic musical studies in Piano, Organ and organ composition, Harpsichord, Composition and Orchestra Conductor. He attended <strong>master classes</strong> studying with G. Scotese, W.Van de Pol, A. Conti, E. Fadini, E. Riboli, L. F. Tagliavini, J. L. Uriol Gonzales, M. Morgan, L. Lombardi, T. Kopman. He has performed in major European cities in the United States of America and the African Continent. His musical interest was always concentrated in a very tender age composition devoted to <strong>research and innovative sounds</strong> with conventional instruments, and with electronic devices by following the evolution of technology, consolidating its <strong>original style, direct and communicative</strong>, aimed at different age public. His music has been broadcast by <strong>Rai Uno, Rai International, Mediaset</strong>, the three Radio RAI, Radio Vaticana and performed in <strong>prestigious international festivals</strong>. He has dedicated and composed music for well known artists on the international scene including Elisabeth Leonskaja, Murray Perahia, Laura De Fusco, W. Van de Pol, Michel Petrucciani and <a href="http://www.antonellaruggiero.com/">Antonella Ruggiero</a>. He also composed music for the Biennale of Venice, the Teatro G. Pergolesi in Jesi Opera season kicking off the 2003/04 with the Opera "Pollici Verdi" and most recently, <a href="http://en.wikipedia.org/wiki/Eugene_Rousseau_%28saxophonist%29">Eugene Rousseau</a>, Ramin Bahrami, and <a href="http://www.stefanobollani.com/">Stefano Bollani</a>.
	
	<?php } ?>
</p>

<h3><?=$lang == 'it' ? 'Composizioni e concorsi a livello internazionale' : 'International compositions and competitions'?></h3>

<p>
	<?php if ($lang == 'it') { // ITA ?>
	
	Vincitore di numerosi <strong>concorsi internazionali di composizione</strong> (fra i tanti: T.I.M. di Parigi edizione 2002; Concorso Internazionale di Composizione "Caffa Righetti" città di Cortemilia - Cuneo, edizione 2003, 2005 e 2006), ha nel suo attivo circa 400 composizioni comprendenti musica per pianoforte, organo, musica da camera in svariate formazioni, musica vocale, sinfonica, sinfonico corale e musica elettronica interattiva con strumenti tradizionali, tra le più significative: <i>Asincrone</i>, per Sequenze Elettroniche e Pianoforte (1989); <i>Concerto in Sol Maggiore</i>, per Flauto e Orchestra d'Archi (1991); <i>Toccata</i>, per Pianoforte (2002); <i>Mosaico Tritonale</i>, per Orchestra Sinfonica (2003); <i>Te Deum</i>, per Soli, Coro, Organo e Orchestra (2003); <i>Magnificat</i>, per Doppio Coro e Organo (2004); <i>Stabat Mater</i>, per Soli, Coro e Orchestra (2006); <i>Paesaggio Umbro</i>, per Violoncello, Quartetto d'Archi, Voci e Pianoforte (2007); <i>Il Cantico delle creature di S. Francesco d'Assisi</i>, Oratorio per Tenore, Coro e Orchestra (2008); <i>San Francesco d'Assisi predica agli uccelli</i>, per Orchestra Sinfonica (2008); <i>Requiem Strumentale</i>, per Saxofono Soprano e Pianoforte (2009); <i>Fantasia Concerto</i>, per Pianoforte e Orchestra (2009); <i>Sei Contrappunti</i>, per Pianoforte I° Volume (2010); <i>Sei Contrappunti</i>, per Pianoforte II° Volume (2012); <i>Dissolvenze Atonali</i>, per Quartetto di Saxofoni, <i>Pianoforte e Sequenza Elettronica</i> (2012).<br>Parte delle sue composizioni sono pubblicate in CD dalle case discografiche Amiata Records, Columbia-Sony, Libera, Rara, Umbria Music Center, mentre la pubblicazione della sua intera opera omnia è curata dalla "Casa Editrice Musicale <a href="http://www.prendinota.eu/">Prendinota</a>".
	
	<?php } else { // ENG ?>
	
	Winner of many <strong>international composition competitions</strong> (Paris T.I.M. edition 2002;  "Caffa Righetti" International Composition Competition Price in Cortemilia - Italy edition 2003, 2005, 2006 and more), has in his credit about 400 compositions including music for piano, organ, chamber music in various ensembles, vocal music, symphonic, choral and symphonic music, interactive electronics with traditional instruments, the most significant: <i>Asincrone</i>, for Electronic Sequences and Piano (1989); <i>Concerto in G Major</i>, for Flute and Strings Orchestra (1991); <i>Toccata</i>, for Piano (2002); <i>Mosaico Tritonale</i>, for Orchestra (2003); <i>Te Deum</i>, for Soloists, Choir, Organ and Orchestra (2003); <i>Magnificat</i>, for Double Choir and Organ (2004); <i>Stabat Mater</i>, for Soloists, Chorus and Orchestra (2006); <i>Paesaggio Umbro</i>, for Cello, Strings Quartet, Voices and Piano (2007); <i>Il cantico delle creature di S. Francesco d'Assisi</i>, Oratorio for Tenor, Chorus and Orchestra (2008); <i>S. Francesco d'Assisi predica agli uccelli</i>, for Orchestra (2008); <i>Requiem strumentale</i>, for Soprano Saxophone and Piano (2009); <i>Fantasia Concerto</i>, for Piano and Orchestra (2009); <i>Sei Contrappunti</i>, for Piano, First Book (2010); <i>Sei Contrappunti</i>, for Piano, Second Book (2012); <i>Dissolvenze Atonali</i>, for Quartet Saxophones, Piano and Electronic Sequence (2012).<br>Part of his compositions are published on CD by record Amiata Records, Columbia-Sony, Libera, Rara, Umbria Music Center, while the publication of his entire music work is curated by "<a href="http://www.prendinota.eu/">Prendinota</a> Music Publishing House."
	
	<?php } ?>
</p>